services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=pass
      - DATABASE_NAME=certificates
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
    depends_on:
      - db
      - rabbitmq
      - redis

  worker:
    build: ./worker
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=pass
      - DATABASE_NAME=certificates
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
    depends_on:
      - db
      - rabbitmq
      - redis  
    volumes:
      - ./worker/src/pdfs:/usr/src/app/worker/src/pdfs # Mapeamento para PDFs

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: certificates
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
 # Definição do volume para os dados do PostgreSQL
  db-data: {} # Apenas define um volume nomeado para o PostgreSQL

  
  
